### PR TITLE
Update effects.cwt

### PR DESCRIPTION
**Pull request by Goldziher**
stnh fix

### CODE REVIEW

**Comment by CaligulaCaesar** [comment]
I want to test this

**Comment by Goldziher** [comment]
well either test and merge, or merge and test - but do this soon.

**Comment by CaligulaCaesar** [comment]
No sir you shall not order me around. I do not find this ok. Modding is something I do in my limited free time. If STNH are interested in CW Tools not showing errors that they think aren't errors, they should do more to help the development of CW Tools - this is not a priority for me!

**Comment by Goldziher** [comment]
Well it might not be a priority for you but you are postponing something I did.

**Comment by CaligulaCaesar** [comment]
It would not be hard for you to make your local version of CW Tools include this. I am actually quite a busy person, I do not always have time to do modding, and when I do I have many different things that I want to do. So you could be a lot more polite when requesting that I test something quickly.

**Pull request merged**
