### PR TITLE
Update star_classes.cwt

### PR DESCRIPTION
**Pull request by Goldziher**
stnh fix

### CODE REVIEW

**Comment by CaligulaCaesar** [comment]
Yeah but really?

**Comment by Goldziher** [comment]
Absolutely, yes.

**Comment by CaligulaCaesar** [comment]
Ok more to the point - why would one do that?

**Comment by Goldziher** [comment]
Well, STNH does it. Why else? Because you might want to place a planet or an entity defined as planet as the center of a system.

Anyhow, this question is merely theoretical - its possible to do in code, hence the tool should support it.

**Pull request merged**
