### PR TITLE
Update traits.cwt

### PR DESCRIPTION
**Pull request by Goldziher**
stnh fix

### CODE REVIEW

**Comment by CaligulaCaesar** [comment]
I want to test whether these work.

**Comment by Goldziher** [comment]
well, test away - but it has been almost a week since you commented and nothing happened.

**Comment by CaligulaCaesar** [comment]
Oh poor you

**Comment by Goldziher** [comment]
Really? I'm writing about the work and you are answering like a child fighting with his sibling..

**Comment by CaligulaCaesar** [comment]
Tested and merged. I was right, sorting priority does nothing for leader traits. So I removed that.

**Pull request merged**
